BEGIN TRY
    BEGIN TRANSACTION;

    PRINT 'Step 10: Mapping Final Correspondents and Upserting Receivers...';

    -- 1. Map the IDs generated by Step 5 / 9 back into our Staging Table
    UPDATE S
    SET ResolvedCorrespondentID = c.CorrespondentID
    FROM master.dbo.Migration_Staging_LetterReceivers S
    INNER JOIN [{{RAHKARAN_DB}}].[GNR3].[Party] p 
        ON LTRIM(RTRIM(p.CompanyName)) COLLATE DATABASE_DEFAULT
         = CAST(S.LetterRecipientTO AS NVARCHAR(100)) COLLATE DATABASE_DEFAULT
    INNER JOIN [{{RAHKARAN_DB}}].[ECM].[Correspondent] c 
        ON c.PartyRef = p.PartyID AND c.[Type] = 1 AND c.State = 1
    WHERE S.ResolvedCorrespondentID IS NULL 
      AND S.LetterRecipientTO IS NOT NULL;

    -- 2. Setup ID Generator for LetterReceiver
    DECLARE @LastID BIGINT;
    SELECT @LastID = LastID
    FROM {{RAHKARAN_DB}}.SYS3.TableIdGen WITH (UPDLOCK, HOLDLOCK)
    WHERE TableName = 'ECM.LetterReceiver';

    IF @LastID IS NULL
    BEGIN
        SET @LastID = 0; 
        INSERT INTO {{RAHKARAN_DB}}.SYS3.TableIdGen (TableName, LastID)
        VALUES ('ECM.LetterReceiver', @LastID);
    END

    IF OBJECT_ID('tempdb..#CandidateReceivers') IS NOT NULL DROP TABLE #CandidateReceivers;
    IF OBJECT_ID('tempdb..#FinalReceiversToInsert') IS NOT NULL DROP TABLE #FinalReceiversToInsert;

    -- 3. Dedup candidate receivers for migrated letters
    SELECT DISTINCT 
        LM.Rahkaran_LetterID AS LetterRef, 
        S.ResolvedCorrespondentID AS ReceiverRef, 
        CAST(S.LetterRecipientTO AS NVARCHAR(250)) AS ReceiverTitle
    INTO #CandidateReceivers
    FROM master.dbo.Migration_Staging_LetterReceivers S
    INNER JOIN master.dbo.Migration_IcanLetter_RahkaranLetter_Map LM
        ON LM.Ican_EntityCode = S.Ican_EntityCode
    WHERE S.ResolvedCorrespondentID IS NOT NULL;

    -- 4. Upsert existing: refresh ReceiverTitle on already-present receivers
    UPDATE LR
    SET
        LR.ReceiverTitle = C.ReceiverTitle,
        LR.LastModifier = 1,
        LR.LastModificationDate = GETDATE()
    FROM {{RAHKARAN_DB}}.ECM.LetterReceiver LR
    INNER JOIN #CandidateReceivers C
        ON C.LetterRef = LR.LetterRef
       AND C.ReceiverRef = LR.ReceiverRef
       AND LR.[Type] = 1
       AND LR.[Order] = 1
    WHERE ISNULL(LR.ReceiverTitle, N'') COLLATE DATABASE_DEFAULT
       <> ISNULL(C.ReceiverTitle, N'') COLLATE DATABASE_DEFAULT;

    DECLARE @UpdatedCount BIGINT = @@ROWCOUNT;

    -- 5. Insert only missing receivers; assign contiguous new IDs
    SELECT
        C.LetterRef,
        C.ReceiverRef,
        C.ReceiverTitle,
        ROW_NUMBER() OVER (ORDER BY C.LetterRef, C.ReceiverRef) AS RN
    INTO #FinalReceiversToInsert
    FROM #CandidateReceivers C
    WHERE NOT EXISTS (
        SELECT 1
        FROM {{RAHKARAN_DB}}.ECM.LetterReceiver LR
        WHERE LR.LetterRef = C.LetterRef
          AND LR.ReceiverRef = C.ReceiverRef
          AND LR.[Type] = 1
          AND LR.[Order] = 1
    );

    DECLARE @InsertedCount BIGINT;
    SELECT @InsertedCount = COUNT(*) FROM #FinalReceiversToInsert;

    IF @InsertedCount > 0
    BEGIN
        INSERT INTO {{RAHKARAN_DB}}.ECM.LetterReceiver (
            LetterReceiverID, LetterRef, ReceiverRef, [Type], [Order], [Description],
            Creator, CreationDate, LastModifier, LastModificationDate, ReceiverTitle
        )
        SELECT
            @LastID + R.RN, R.LetterRef, R.ReceiverRef, 1, 1, NULL, 
            1, GETDATE(), 1, GETDATE(), R.ReceiverTitle
        FROM #FinalReceiversToInsert R;

        UPDATE {{RAHKARAN_DB}}.SYS3.TableIdGen
        SET LastID = @LastID + @InsertedCount
        WHERE TableName = 'ECM.LetterReceiver';
    END

    -- 6. Update Letter Types — scoped to migrated letters only
    UPDATE l
    SET LetterType = 3 
    FROM {{RAHKARAN_DB}}.ECM.letter l
    INNER JOIN master.dbo.Migration_IcanLetter_RahkaranLetter_Map M
        ON M.Rahkaran_LetterID = l.LetterID
    INNER JOIN {{RAHKARAN_DB}}.ECM.LetterReceiver lr
        ON lr.LetterRef = l.LetterID
    INNER JOIN {{RAHKARAN_DB}}.ECM.Correspondent c
        ON c.CorrespondentID = lr.ReceiverRef
    WHERE c.[Type] = 7;

    UPDATE l
    SET LetterType = 2 
    FROM {{RAHKARAN_DB}}.ECM.letter l
    INNER JOIN master.dbo.Migration_IcanLetter_RahkaranLetter_Map M
        ON M.Rahkaran_LetterID = l.LetterID
    WHERE l.LetterType != 3;

    -- Keep letter ID generator at least at max(LetterID)
    DECLARE @MaxLetterID BIGINT;
    SELECT @MaxLetterID = ISNULL(MAX(LetterID), 0) FROM {{RAHKARAN_DB}}.ECM.Letter;

    UPDATE {{RAHKARAN_DB}}.SYS3.TableIdGen
    SET LastID = CASE WHEN @MaxLetterID > LastID THEN @MaxLetterID ELSE LastID END
    WHERE TableName = 'ECM.Letter';

    COMMIT TRANSACTION;
    PRINT 'Step 10 Complete. Receivers updated: '
        + CAST(@UpdatedCount AS VARCHAR)
        + ', inserted: ' + CAST(ISNULL(@InsertedCount, 0) AS VARCHAR);
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
