BEGIN TRY
    BEGIN TRANSACTION;

    PRINT 'Step 10: Mapping Final Correspondents and Inserting Receivers...';

    -- 1. Map the IDs generated by Step 5 back into our Staging Table
    UPDATE S
    SET ResolvedCorrespondentID = c.CorrespondentID
    FROM master.dbo.Migration_Staging_LetterReceivers S
    INNER JOIN [{{RAHKARAN_DB}}].[GNR3].[Party] p 
        -- FIXED: We must also truncate the JOIN to 100 characters so it matches what we inserted in Step 9
        ON LTRIM(RTRIM(p.CompanyName)) COLLATE DATABASE_DEFAULT = CAST(S.LetterRecipientTO AS NVARCHAR(100)) COLLATE DATABASE_DEFAULT
    INNER JOIN [{{RAHKARAN_DB}}].[ECM].[Correspondent] c 
        ON c.PartyRef = p.PartyID AND c.[Type] = 1 AND c.State = 1
    WHERE S.ResolvedCorrespondentID IS NULL 
      AND S.LetterRecipientTO IS NOT NULL;

    -- 2. Setup ID Generator for LetterReceiver
    DECLARE @LastID BIGINT;
    SELECT @LastID = LastID FROM {{RAHKARAN_DB}}.SYS3.TableIdGen WITH (UPDLOCK, HOLDLOCK) WHERE TableName = 'ECM.LetterReceiver';

    IF @LastID IS NULL
    BEGIN
        SET @LastID = 0; 
        INSERT INTO {{RAHKARAN_DB}}.SYS3.TableIdGen (TableName, LastID) VALUES ('ECM.LetterReceiver', @LastID);
    END

    IF OBJECT_ID('tempdb..#FinalReceiversToInsert') IS NOT NULL DROP TABLE #FinalReceiversToInsert;

    -- 3. Dedup the records
    SELECT DISTINCT 
        LM.Rahkaran_LetterID AS LetterRef, 
        S.ResolvedCorrespondentID AS ReceiverRef, 
        -- FIXED: Safely truncate the ReceiverTitle to prevent an overflow crash on the final insert
        CAST(S.LetterRecipientTO AS NVARCHAR(250)) AS ReceiverTitle,
        ROW_NUMBER() OVER (ORDER BY LM.Rahkaran_LetterID, S.ResolvedCorrespondentID) AS RN
    INTO #FinalReceiversToInsert
    FROM master.dbo.Migration_Staging_LetterReceivers S
    INNER JOIN master.dbo.Migration_IcanLetter_RahkaranLetter_Map LM ON LM.Ican_EntityCode = S.Ican_EntityCode
    WHERE S.ResolvedCorrespondentID IS NOT NULL;

    -- 4. Insert into Rahkaran LetterReceiver
    INSERT INTO {{RAHKARAN_DB}}.ECM.LetterReceiver (
        LetterReceiverID, LetterRef, ReceiverRef, [Type], [Order], [Description],
        Creator, CreationDate, LastModifier, LastModificationDate, ReceiverTitle
    )
    SELECT
        @LastID + R.RN, R.LetterRef, R.ReceiverRef, 1, 1, NULL, 
        1, GETDATE(), 1, GETDATE(), R.ReceiverTitle
    FROM #FinalReceiversToInsert R
    WHERE NOT EXISTS (
        SELECT 1 FROM {{RAHKARAN_DB}}.ECM.LetterReceiver LR
        WHERE LR.LetterRef = R.LetterRef AND LR.ReceiverRef = R.ReceiverRef AND LR.[Type] = 1 AND LR.[Order] = 1
    );

    DECLARE @InsertedCount BIGINT = @@ROWCOUNT;

    IF @InsertedCount > 0
    BEGIN
        UPDATE {{RAHKARAN_DB}}.SYS3.TableIdGen
        SET LastID = @LastID + @InsertedCount
        WHERE TableName = 'ECM.LetterReceiver';
    END

    -- 5. Update Letter Types
    UPDATE l
    SET LetterType = 3 
    FROM {{RAHKARAN_DB}}.ECM.letter l
    INNER JOIN {{RAHKARAN_DB}}.ECM.LetterReceiver lr ON lr.LetterRef = l.LetterID
    INNER JOIN {{RAHKARAN_DB}}.ECM.Correspondent c ON c.CorrespondentID = lr.ReceiverRef
    WHERE c.[Type] = 7;

    UPDATE {{RAHKARAN_DB}}.ECM.letter 
    SET LetterType = 2 
    WHERE LetterType != 3;

    UPDATE {{RAHKARAN_DB}}.SYS3.TableIdGen 
    SET LastID = (SELECT ISNULL(MAX(LetterID), 0) + 1 FROM {{RAHKARAN_DB}}.ECM.Letter)  
    WHERE TableName = 'ECM.Letter';

    COMMIT TRANSACTION;
    PRINT 'Step 10 Complete. All Receivers successfully migrated.';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO